version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"     # App port
      - "9229:9229"     # Debugger port
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start:debug