services:
  auth_commands_db:
    image: postgres:17-alpine
    container_name: auth_commands_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_commands_db
    volumes:
      - auth_commands_db_pg_data:/var/lib/postgresql/data
    networks:
      - monitor-net

  analytics_queries_db:
    image: postgres:17-alpine
    container_name: analytics_queries_db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_queries_db
    volumes:
      - analytics_queries_db_pg_data:/var/lib/postgresql/data
    networks:
      - monitor-net

  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5673:5672' # RabbitMQ server
      - '15673:15672' # RabbitMQ UI
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq.definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - monitor-net

volumes:
  auth_commands_db_pg_data:
  analytics_queries_db_pg_data:

networks:
  monitor-net:
    driver: bridge
