version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"     # App port
      - "9229:9229"     # Debugger port
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start:debug

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - monitor-net